apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-ccgb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-ccgb
    app.kubernetes.io/part-of: jvm-build-suite-application-itkc
  name: jvm-build-suite-component-ccgb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-ccgb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-ccgb
    spec:
      containers:
      - image: quay.io/qijing/jvm-build-pdzb-tenant/jvm-build-suite-application-itkc/jvm-build-suite-component-ccgb@sha256:a8273946d35c6044cabfcc197225f65164d08a4d63e283fdbe910e700a653078
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
